version: 0.2
phases:
  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore src/code/BookStore.ProductService/BookStore.ProductService.csproj
  build:
    commands:
      - echo Build started on `date`
      - dotnet publish -c release -o ./build_output src/code/BookStore.ProductService/BookStore.ProductService.csproj
artifacts:
  files:
    - CodeBuild-BookStore/build_output/**/*